# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
      
          ls
          shopt -s nullglob
          numfiles=(*)
          numfiles=${#numfiles[@]}
                                  
          echo "##vso[task.setvariable variable=buildCacheFiles]bakamitai"
          echo "the number of files is $(buildCacheFiles)"
    workingDirectory: 'art'
  displayName: 'Run a multi-line script'
